### ISSUE TITLE
Here new Idea for this project

### ISSUE THREAD

**Issue by UserGhost411** [arsyadbruh/resep-app-wih-react-native#1]
here new idea:
- [ ]  AI system
- [ ]  Automatic Robot System
- [ ]  Smarthome Integration
- [ ]  Connect to Brain Nerve

**Comment by UserGhost411** [comment]
add to PR @arsyadbruh

**Comment by arsyadbruh** [comment]
thanks for the suggestion. 
we can't do that at the moment, though we will consider it if needed.
